Wrapper class file
E3-JSI/PREPARE-anonipy pull request #4
Opened 2024-11-21 08:40 UTC by ninakokalj

This PR is for the wrapper class, which gets the extractors and anonymization strategy as the input, and has methods for traversing across folders and files and applying the anonymization pipeline on the files.

---

Closes:
#1

2024-11-21 13:40 UTC, eriknovak requested changes
Generally, the code looks good! I added syntactic comments, which should be addressed. The comments labeled as [Question] is something to think about and [Future work] is something to have in mind for the future (as a possible future task).

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +import os
Order the imports in the following order: 

1. Python native modules
2. Installed modules via requirements.txt
3. Implemented modules

```python
import os
import json
from typing import Union, List

from .anonymize.extractors import ExtractorInterface, MultiExtractor
from .anonymize.strategies import StrategyInterface
from .utils.file_system import open_file, write_file
```

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +from .utils.file_system import *
Never import all functions using star `*`. It can happen that another module also imports the same-named functions, and you then do not know which is which.

Better to import the actual functions as:

```python
from .utils.file_system import open_file, write_file
```

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +class Pipeline():
In Python, no need for brackets if the class does not inherit from another class. Please update to:
```python
class Pipeline:
    ...
```

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +            anonymize(input_dir, output_dir, flatten=False): Anonymize files in the input directory and save the anonymized files to the output directory.
Put the description in new line:

```
anonymize(input_dir, output_dir, flatten=False): 
    Anonymize files in the input directory and save the anonymized files to the output directory. 
```

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +                self.extractor = MultiExtractor(extractor)
[Question] What happens when the extractor is a list containing a `MultiExtractor`? Will this line then be:

```python
self.extractor = MultiExtractor([MultiExtractor(...)])
```

Are there any unforeseen consequences?

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +                extractor (Union[ExtractorInterface, List[ExtractorInterface]]): The extractor to use for entity extraction.
In the arguments, there is no need for specifying the argument type, as it is already defined in the function. Please remove all types from the `Args` in all documentations (see other methods in anonipy how it is defined).

Note that the `Attributes` in the class description should have the specified types.

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +                input_dir (str): The path to the input directory containing files to be anonymized.
In the arguments, there is no need for specifying the argument type, as it is already defined in the function. Please remove all types from the Args in all documentations (see other methods in anonipy how it is defined).

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +                file_path (str): The path to the file to be anonymized.
In the arguments, there is no need for specifying the argument type, as it is already defined in the function. Please remove all types from the Args in all documentations (see other methods in anonipy how it is defined).

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +            return ""
It might be worth to discuss/look what to return if the original_text is `None`. Should be actually return an empty string or would it be better to be `None` (i.e. do not generate an anonymized file).

I am more for the `None` option - this way the final list of documents will be the list of only the documents, which were successfully anonymized, without any potential "weird" files.

@ninakokalj What do you think?

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +            return ""
[Question] It might be worth to discuss/look what to return if the original_text is `None`. Should be actually return an empty string or would it be better to be `None` (i.e. do not generate an anonymized file).

I am more for the `None` option - this way the final list of documents will be the list of only the documents, which were successfully anonymized, without any potential "weird" files.

@ninakokalj What do you think?

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +            print(f"Skipping file {file_path}: Failed to read or file is empty.")
[Future work] Use a different way of printing/logging information about the problems within the package.

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +            print(f"Skipping file {file_path}: Entity extraction returned None.")
[Future work] Use a different way of printing/logging information about the problems within the package.

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +            >>> pipeline.anonymize(r"/path/to/input_dir", r"/path/to/output_dir", False)
Make the example line more descriptive:
```bash
>>> pipeline.anonymize("/path/to/input_dir", "/path/to/output_dir", flatten=False)  
```
Also, do we need the regex expression flag (`r"..."`) to specify the folder paths?

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +        if os.path.abspath(input_dir) == os.path.abspath(output_dir):
Can we move this if statement before the `output_dir` creation commands? So that we do not create the directory before validating if the `input_dir` and `output_dir` folders are the same.

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +                        print(f"Skipping file {file_path}: Anonymized text is empty.")
[Future work] Use a different way of printing/logging information about the problems within the package.

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +                    print(f"Error processing file {file_path}: {e}")
[Future work] Use a different way of printing/logging information about the problems within the package.

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +                self.anonymized_files_count += 1
Increment the value of `self.anonymized_files_count` after the file is written.

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +                base_name, ext = os.path.splitext(file_name)
I think you do not need this `base_name`, because you override it afterwards. If that is true, you can rewrite the line to:

```python
_, ext = os.path.splitext(file_name)
```

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +                output_file_name = f"{base_name}_anony{ext}"
You can potentially merge the upper two lines to create the output_file_name:

```python
output_file_name = f"file{self.anonymized_files_count}_anony{ext}"
```
Consider setting the variable `self.anonymized_files_count` as a variable defined in the `anonymize` function (so to have `anonymized_files_count` instead of `self.anonymized_files_count`).

2024-11-21 13:40 UTC, eriknovak commented on anonipy/pipeline.py
> +        return json.dumps(file_name_mapping, indent=4, sort_keys=True)
No need to return a string representation of `file_name_mapping`. I would suggest returning it in `dict` format.

2024-11-21 20:17 UTC, ninakokalj commented on anonipy/pipeline.py
> +            return ""
I agree, I’m also in favor of not writing files that were unsuccessfully anonymized. I check in the `anonymize` method if the string I get from `_anonymize_file` (the `anonymized_text` variable) is empty. If it is empty, I skip it and do not write it. But I could do it your way and return `None` if you'd prefer that approach for handling these cases.

2024-11-22 08:53 UTC, ninakokalj commented on anonipy/pipeline.py
> +                self.extractor = MultiExtractor(extractor)
I fixed the Pipeline class to be able do take `MultiExtractor` aswell, however if I understand the code correctly the `MultiExctractor class` only takes a `List[ExtractorInterface]` as an attribute and `MultiExtractor` is not an instance of `ExtractorInterface class`, so `MultiExtractor([MultiExtractor(...)])` is not possible.

2024-11-22 09:35 UTC, ninakokalj commented
I’ve made the requested changes. I’ve added the option to initialize the Pipeline class with the Multiextractor and changed the method `_anonymize_file(self, file_path: str) -> Union[str, None]` to now return `None` if the text is empty or the extraction filed. Please take another look when you have time!

2024-11-22 14:25 UTC, eriknovak approved these changes
Looks good. Merging.

2024-11-22 14:25 UTC, merged