Better date generation handling
E3-JSI/PREPARE-anonipy pull request #7
Opened 2024-12-02 21:09 UTC by ninakokalj

This pull request modifies the `DateGenerator` class and the `detect_datetime_format` function it uses to detect the format of the original date, ensuring that the anonymized date is formatted in the same way. 

I updated `detect_datetime_format` to handle all 9 supported languages by utilizing `dateparser.parse()` to convert the string representation of the date into a `datetime` object. Then, I used `format_datetime` from `babel.dates` to format the date back into a string.

Additionally, I modified the `DateGenerator` class to accept a `language` argument, which specifies the language of the text to be anonymized. I also updated the class's `generate` method to use `format_datetime` from `babel.dates` for formatting the anonymized date.

---

Closes #2

2024-12-03 20:09 UTC, eriknovak requested changes
Generally looks good! There are some comments that I think need to be addressed.

Also, the packages `babel` and `dateparser` are not added to the `requirements.txt` file. Please add them. Otherwise, `anonipy` will throw errors when processing dates.

2024-12-03 20:09 UTC, eriknovak commented on anonipy/anonymize/generators/date_generator.py
> +from ...constants import LANGUAGES
Merge the two `from ...constants import ...` together, i.e.:

```python
from ...constants import DATE_TRANSFORM_VARIANTS, LANGUAGES
```

2024-12-03 20:09 UTC, eriknovak commented on anonipy/anonymize/generators/date_generator.py
> +    def __init__(self, *args, date_format: str = "auto", lang: Union[str, LANGUAGES] = "en", day_sigma: int = 30, **kwargs):
Reorder the input parameters:

```python
def __init__(self, *args, lang: Union[str, LANGUAGES] = "en", date_format: str = "auto", day_sigma: int = 30, **kwargs):
```

2024-12-03 20:09 UTC, eriknovak commented on anonipy/anonymize/generators/date_generator.py
> +            lang: The language of the text.
Reorder the Args to reflect the input order.

2024-12-03 20:09 UTC, eriknovak commented on anonipy/anonymize/generators/date_generator.py
> +        if isinstance(lang, str) and lang in ["en", "de", "el", "nl", "fr", "it", "sl", "es", "uk"]:
Can we form the list of languages automatically? So that when we add new languages, we do not need to modify this code. 

Is it possible to create the list from the supported `LANGUAGES` values?

2024-12-03 20:09 UTC, eriknovak commented on anonipy/anonymize/generators/date_generator.py
>          self.day_sigma = day_sigma
Move this line below the line with the `self.date_format = date_format`.

2024-12-03 20:09 UTC, eriknovak commented on anonipy/utils/datetime.py
>      Args:
Missing `lang` argument in documentation.

2024-12-03 20:09 UTC, eriknovak commented on anonipy/utils/datetime.py
> +    datetime = re.sub(r"1°", '1', datetime)
Change single quotes to double quotes.

2024-12-03 20:09 UTC, eriknovak commented on anonipy/utils/datetime.py
> +
Remove whitespaces.

2024-12-03 20:09 UTC, eriknovak commented on anonipy/utils/datetime.py
> +    datetime = re.sub(r"\bроку\b", "", datetime).strip()
I would add all of this datetime formatting (between lines 132 and 151) into a separate function to format the datetime string.

2024-12-05 15:36 UTC, ninakokalj commented
I've implemented the requested changes. Please let me know if there's anything else you'd like adjusted.

2024-12-06 07:10 UTC, eriknovak requested changes
The code looks better! One suggestion would tidy up the code (I annotated it as [B]). Once that is done, it should be ready to be merged.

2024-12-06 07:10 UTC, eriknovak commented on anonipy/constants.py
> +SUPPORTED_LANGUAGES = [value[0] for attr, value in LANGUAGES.__dict__.items() if not attr.startswith("_") and isinstance(value, tuple)]
[B] I would suggest to add `supported_languages` as a class method of `LANGUAGES`:

```python
class LANGUAGES:
    ...

    @classmethod
    def supported_languages(self) -> List[str]:
        """Return a list of all supported languages.

        Returns:
            The list of all supported languages.

        """
        return [lang[0] for lang in self.__dict__.values() if isinstance(lang, tuple)]
```

And then change all the appropriate files to use it.

2024-12-06 07:10 UTC, eriknovak commented on anonipy/utils/datetime.py
> +        lang: The language of the datetime string.
Add empty line below `lang`.

2024-12-06 07:10 UTC, eriknovak commented on anonipy/anonymize/generators/date_generator.py
> +from ...constants import DATE_TRANSFORM_VARIANTS, LANGUAGES, SUPPORTED_LANGUAGES
Given the comment [B] (see below), remove `SUPPORTED_LANGUAGES`.

2024-12-06 07:10 UTC, eriknovak commented on anonipy/anonymize/generators/date_generator.py
> +        if isinstance(lang, str) and lang in SUPPORTED_LANGUAGES:
Given the comment [B] (see below), change the line to:

```python
if isinstance(lang, str) and lang in LANGUAGES.supported_languages():
    ...
```

2024-12-10 10:54 UTC, ninakokalj commented
I have implemented the requested changes and renamed the file from `anonipy/utils/datetime.py` to `anonipy/utils/datetime_format.py`. Since I wasn't sure of a better approach, I deleted the old file and created the new one directly in Git.

2024-12-10 17:51 UTC, eriknovak approved these changes
Looks good! Merging.

2024-12-10 17:51 UTC, merged